config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :suppliers
  resources :purchases
  resources :sales
  resources :categories
  resources :drugs
  devise_for :users
  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/drug.rb
class Drug < ApplicationRecord
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_drug, only: [:show, :edit, :update, :destroy]

  # GET /drugs
  # GET /drugs.json
  def index
    @drugs = Drug.all
  end

  # GET /drugs/1
  # GET /drugs/1.json
  def show
  end

  # GET /drugs/new
  def new
    @drug = Drug.new
  end

  # GET /drugs/1/edit
  def edit
  end

  # POST /drugs
  # POST /drugs.json
  def create
    @drug = Drug.new(drug_params)

    respond_to do |format|
      if @drug.save
        format.html { redirect_to @drug, notice: 'Drug was successfully created.' }
        format.json { render :show, status: :created, location: @drug }
      else
        format.html { render :new }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drugs/1
  # PATCH/PUT /drugs/1.json
  def update
    respond_to do |format|
      if @drug.update(drug_params)
        format.html { redirect_to @drug, notice: 'Drug was successfully updated.' }
        format.json { render :show, status: :ok, location: @drug }
      else
        format.html { render :edit }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drugs/1
  # DELETE /drugs/1.json
  def destroy
    @drug.destroy
    respond_to do |format|
      format.html { redirect_to drugs_url, notice: 'Drug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drug
      @drug = Drug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drug_params
      params.require(:drug).permit(:name, :qty, :unit, :price_per_unit)
    end
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/views/drugs/_form.html.slim
= form_for @drug do |f|
  - if @drug.errors.any?
    #error_explanation
      h2 = "#{pluralize(@drug.errors.count, "error")} prohibited this drug from being saved:"
      ul
        - @drug.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :qty
    = f.number_field :qty
  .field
    = f.label :unit
    = f.number_field :unit
  .field
    = f.label :price_per_unit
    = f.text_field :price_per_unit
  .actions = f.submit

app/views/drugs/edit.html.slim
h1 Editing drug

== render 'form'

= link_to 'Show', @drug
'  |
= link_to 'Back', drugs_path

app/views/drugs/index.html.slim
h1 Listing drugs

table
  thead
    tr
      th Name
      th Qty
      th Unit
      th Price per unit
      th
      th
      th

  tbody
    - @drugs.each do |drug|
      tr
        td = drug.name
        td = drug.qty
        td = drug.unit
        td = drug.price_per_unit
        td = link_to 'Show', drug
        td = link_to 'Edit', edit_drug_path(drug)
        td = link_to 'Destroy', drug, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Drug', new_drug_path

app/views/drugs/new.html.slim
h1 New drug

== render 'form'

= link_to 'Back', drugs_path

app/views/drugs/show.html.slim
p#notice = notice

p
  strong Name:
  = @drug.name
p
  strong Qty:
  = @drug.qty
p
  strong Unit:
  = @drug.unit
p
  strong Price per unit:
  = @drug.price_per_unit

= link_to 'Edit', edit_drug_path(@drug)
'  |
= link_to 'Back', drugs_path