config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :suppliers
  resources :purchases
  resources :sales
  resources :categories
  resources :drugs
  devise_for :users
  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:total, :date)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.slim
= form_for @sale do |f|
  - if @sale.errors.any?
    #error_explanation
      h2 = "#{pluralize(@sale.errors.count, "error")} prohibited this sale from being saved:"
      ul
        - @sale.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :total
    = f.text_field :total
  .field
    = f.label :date
    = f.date_select :date
  .actions = f.submit

app/views/sales/edit.html.slim
h1 Editing sale

== render 'form'

= link_to 'Show', @sale
'  |
= link_to 'Back', sales_path

app/views/sales/index.html.slim
h1 Listing sales

table
  thead
    tr
      th Total
      th Date
      th
      th
      th

  tbody
    - @sales.each do |sale|
      tr
        td = sale.total
        td = sale.date
        td = link_to 'Show', sale
        td = link_to 'Edit', edit_sale_path(sale)
        td = link_to 'Destroy', sale, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Sale', new_sale_path

app/views/sales/new.html.slim
h1 New sale

== render 'form'

= link_to 'Back', sales_path

app/views/sales/show.html.slim
p#notice = notice

p
  strong Total:
  = @sale.total
p
  strong Date:
  = @sale.date

= link_to 'Edit', edit_sale_path(@sale)
'  |
= link_to 'Back', sales_path